--- #YAML:1.0
name:                Data-Object-AutoWrap
version:             0.01
abstract:            Autogenerate accessors for R/O object data
license:             perl
author:              
    - Andy Armstrong <andy.armstrong@messagesystems.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
